export const SHORE_DISTRICTS: Record<string, Record<string, string[]>> = {
  "Лівий берег": {
    en: ["Dniprovskyi", "Darnytskyi", "Desnyanskyi"],
    ua: ["Дніпровський", "Дарницький", "Деснянський"],
  },
  "Правий берег": {
    en: [
      "Pecherskyi",
      "Shevchenkivskyi",
      "Podilskyi",
      "Holosiivskyi",
      "Solomianskyi",
      "Obolonskyi",
      "Sviatoshynskyi",
    ],
    ua: [
      "Печерський",
      "Шевченківський",
      "Подільський",
      "Голосіївський",
      "Солом'янський",
      "Оболонський",
      "Святошинський",
    ],
  },
};

export const METRO_LINES: Record<string, Record<string, string[]>> = {
  "Червона лінія": {
    en: [
      "Akademmistechko",
      "Zhytomyrska",
      "Sviatoshyn",
      "Nyvky",
      "Beresteiska",
      "Shuliavska",
      "Politechnichnyi Instytut",
      "Vokzalna",
      "Universytet",
      "Teatralna",
      "Khreshchatyk",
      "Arsenalna",
      "Dnipro",
      "Hidropark",
      "Livoberezhna",
      "Darnytsia",
      "Chernihivska",
      "Lisova",
    ],
    ua: [
      "Академмістечко",
      "Житомирська",
      "Святошин",
      "Нивки",
      "Берестейська",
      "Шулявська",
      "Політехнічний інститут",
      "Вокзальна",
      "Університет",
      "Театральна",
      "Хрещатик",
      "Арсенальна",
      "Дніпро",
      "Гідропарк",
      "Лівобережна",
      "Дарниця",
      "Чернігівська",
      "Лісова",
    ],
  },
  "Синя лінія": {
    en: [
      "Heroiv Dnipra",
      "Minska",
      "Obolon",
      "Pochaina",
      "Tarasa Shevchenka",
      "Kontraktova Ploshcha",
      "Poshtova Ploshcha",
      "Maidan Nezalezhnosti",
      "Ukrainian Heroes Square",
      "Olimpiiska",
      "Palats Ukraina",
      "Lybidska",
      "Demiyivska",
      "Holosiivska",
      "Vasylkivska",
      "Vystavkovyi Tsentr",
      "Iprodrom",
      "Teremky",
    ],
    ua: [
      "Героїв Дніпра",
      "Мінська",
      "Оболонь",
      "Почайна",
      "Тараса Шевченка",
      "Контрактова площа",
      "Поштова площа",
      "Майдан Незалежності",
      "Площа Українських Героїв",
      "Олімпійська",
      "Палац «Україна»",
      "Либідська",
      "Деміївська",
      "Голосіївська",
      "Васильківська",
      "Виставковий центр",
      "Іподром",
      "Теремки",
    ],
  },
  "Зелена лінія": {
    en: [
      "Syrets",
      "Dorohozhychi",
      "Lukianivska",
      "Zoloti Vorota",
      "Palats Sportu",
      "Klovska",
      "Pecherska",
      "Zvirynetska",
      "Vydubychi",
      "Slavutych",
      "Osokorky",
      "Pozniaky",
      "Kharkivska",
      "Vyrlytsia",
      "Boryspilska",
      "Chervonyi Khutir",
    ],
    ua: [
      "Сирець",
      "Дорогожичі",
      "Лук'янівська",
      "Золоті ворота",
      "Палац спорту",
      "Кловська",
      "Печерська",
      "Звіринецька",
      "Видубичі",
      "Славутич",
      "Осокорки",
      "Позняки",
      "Харківська",
      "Вирлиця",
      "Бориспільська",
      "Червоний Хутір",
    ],
  },
};
